### ISSUE TITLE
Don't show login page after logging out

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/console.dot#50]
In our setup the login page cannot work, due to our usage of `--local-session`. Instead, after the session ends we should just show some "Nothing to see here, please close" page without any actions.

This will have to be changed in cockpit-ws itself and thus reassigned. But filing it here first for tracking the outstanding issues.

**Comment by martinpitt** [comment]
Actually, we *can* handle this on our side -- after fixing #6 we can just set the session status to `closed`, and let our "session not running" page DTRT for this status.

**Comment by martinpitt** [comment]
Fixed in PR #48

**Comment by marusak** [comment]
We also should disable/remove the logout button from the UI.

**Comment by martinpitt** [comment]
@marusak : Why? It's actually nice to have it now IMHO. You click "Logout" and directly see the "your session is closed" page after PR #48. Go ahead and try it :grin:

**Comment by marusak** [comment]
It might give people "hope" that they can re-login as different user. It might be a surprise for them to learn that they will have to establish the session from scratch when they log out.

Agree it is nice when you end the session and see the "end" page. But maybe we should not have "log out" button but "end session" or so? So people actually have a "safe" way of ending this session rather than closing the tab and hoping that the connection is available anymore.

**Comment by martinpitt** [comment]
Hmm, it actually feels safer to me to explicitly logout rather than just closing the tab and relying on the timeout. You'll get an automatic logout after ~ 15 seconds (our tests cover that), but the user won't have that warm fuzzy feeling. Well, I don't veto changing cockpit to not show a Logout when using `--local-session`, but I don't exactly promote it either. I think I'll leave that decision up to you :grin:

**Comment by marusak** [comment]
> Hmm, it actually feels safer to me to explicitly logout rather than just closing the tab and relying on the timeout.

Agree

What I was suggesting was to rename "Logout" to "End session" for this usecase in the UI to make it clear what will happen.
